CREATE SEQUENCE seq_board
    START WITH 1
    INCREMENT BY 1
    NOCACHE;

CREATE TABLE TBL_LOCATION
(
    LOCATION_ID NUMBER PRIMARY KEY,
    CITY        VARCHAR2(100)   NOT NULL,
    STREET      VARCHAR2(100)   NOT NULL,
    DETAIL      VARCHAR2(100),
    POSTAL_CODE VARCHAR2(100)   NOT NULL
);

CREATE TABLE TBL_ORGANIZATION
(
    ORGANIZATION_ID            NUMBER PRIMARY KEY,
    LOCATION_ID         NUMBER    NOT NULL,
    NAME         VARCHAR2(100)    NOT NULL,
    PHONE_NUMBER       VARCHAR2(100)   NOT NULL,
    TELEPHONE_NUMBER   VARCHAR2(100)   NOT NULL,
    REGISTER_DATE DATE   DEFAULT SYSDATE,
    UPDATE_DATE   DATE   DEFAULT SYSDATE,
    PROVIDER_ID         VARCHAR2(255),
    CONSTRAINT FK_ORGANIZATION_TO_LOCATION FOREIGN KEY (LOCATION_ID)
        REFERENCES TBL_LOCATION (LOCATION_ID) ON DELETE CASCADE
);

CREATE TABLE TBL_USER
(
    USER_ID            NUMBER PRIMARY KEY,
    LOCATION_ID         NUMBER    NOT NULL,
    PROVIDER_ID         VARCHAR2(255),
    NAME         VARCHAR2(100)    NOT NULL,
    PHONE_NUMBER       VARCHAR2(100)   NOT NULL,
    EMAIL       VARCHAR2(100)   NOT NULL,
    EMAIL_APPROVE  CHAR(1)   NOT NULL,
    PHONE_APPROVE  CHAR(1)   NOT NULL,
    INTRODUCTION       VARCHAR2(500)   NOT NULL,
    REGISTER_DATE DATE   DEFAULT SYSDATE,

    CONSTRAINT FK_USER_TO_LOCATION FOREIGN KEY (LOCATION_ID)
        REFERENCES TBL_LOCATION (LOCATION_ID) ON DELETE CASCADE
);

CREATE TABLE TBL_VOLUNTEER
(
    VOLUNTEER_ID            NUMBER PRIMARY KEY,
    LOCATION_ID         NUMBER    NOT NULL,
    ORGANIZATION_ID         NUMBER    NOT NULL,
    TITLE         VARCHAR2(100)    NOT NULL,
    CONTENT       VARCHAR2(1000)   NOT NULL,
    CATEGORY   VARCHAR2(100)   NOT NULL,
    TARGET   VARCHAR2(100)   NOT NULL,
    RECRUIT_START_DATE DATE DEFAULT SYSDATE,
    RECRUIT_END_DATE   DATE NOT NULL ,
    RECRUIT_NUMBER     NUMBER,
    IS_ADULT_ALLOWED CHAR(1) DEFAULT 1,
    IS_TEEN_ALLOWED CHAR(1) DEFAULT 1,
    VOLUNTEER_DATE DATE NOT NULL,
    CONSTRAINT FK_VOLUNTEER_TO_LOCATION FOREIGN KEY (LOCATION_ID)
        REFERENCES TBL_LOCATION (LOCATION_ID) ON DELETE CASCADE,
    CONSTRAINT FK_VOLUNTEER_TO_ORGANIZATION FOREIGN KEY (ORGANIZATION_ID)
        REFERENCES TBL_ORGANIZATION (ORGANIZATION_ID) ON DELETE CASCADE
);

CREATE TABLE TBL_APPLIED_VOLUNTEER
(
    APPLIED_VOLUNTEER_ID   NUMBER PRIMARY KEY,
    VOLUNTEER_ID          NUMBER    NOT NULL,
    USER_ID          NUMBER    NOT NULL,
    APPLIED_DATE   DATE NOT NULL ,
    STATUS VARCHAR2(100) NOT NULL,
    CONSTRAINT FK_APPLIED_VOLUNTEER_TO_VOLUNTEER FOREIGN KEY (VOLUNTEER_ID)
        REFERENCES TBL_VOLUNTEER (VOLUNTEER_ID) ON DELETE CASCADE,
    CONSTRAINT FK_APPLIED_VOLUNTEER_TO_USER FOREIGN KEY (USER_ID)
        REFERENCES TBL_USER (USER_ID) ON DELETE CASCADE
);

CREATE TABLE TBL_USER_ALARM
(
    USER_ALARM_ID   NUMBER PRIMARY KEY,
    USER_ID          NUMBER    NOT NULL,
    TITLE VARCHAR2(100) NOT NULL ,
    CONTENT VARCHAR2(1000) NOT NULL ,
    STATUS VARCHAR2(100) NOT NULL,
    CONSTRAINT FK_USER_ALARM_TO_USER FOREIGN KEY (USER_ID)
        REFERENCES TBL_USER (USER_ID) ON DELETE CASCADE
);

CREATE TABLE TBL_ORGANIZATION_ALARM
(
    ORGANIZATION_ALARM_ID   NUMBER PRIMARY KEY,
    ORGANIZATION_ID          NUMBER    NOT NULL,
    TITLE VARCHAR2(100) NOT NULL ,
    CONTENT VARCHAR2(1000) NOT NULL ,
    STATUS VARCHAR2(100) NOT NULL,
    CONSTRAINT FK_USER_ALARM_TO_ORGANIZATION FOREIGN KEY (ORGANIZATION_ID)
        REFERENCES TBL_ORGANIZATION (ORGANIZATION_ID) ON DELETE CASCADE
);

CREATE TABLE TBL_USER_REVIEW
(
    USER_REVIEW_ID   NUMBER PRIMARY KEY,
    USER_ID          NUMBER    NOT NULL,
    ORGANIZATION_ID          NUMBER    NOT NULL,
    CONTENT VARCHAR2(1000) NOT NULL ,
    RATING NUMBER NOT NULL,
    CONSTRAINT FK_USER_REVIEW_TO_USER FOREIGN KEY (USER_ID)
        REFERENCES TBL_USER (USER_ID) ON DELETE CASCADE,
    CONSTRAINT FK_USER_REVIEW_TO_ORGANIZATION FOREIGN KEY (ORGANIZATION_ID)
        REFERENCES TBL_ORGANIZATION (ORGANIZATION_ID) ON DELETE CASCADE
);

CREATE TABLE TBL_ORGANIZATION_REVIEW
(
    ORGANIZATION_REVIEW_ID   NUMBER PRIMARY KEY,
    ORGANIZATION_ID          NUMBER    NOT NULL,
    USER_ID          NUMBER    NOT NULL,
    CONTENT VARCHAR2(1000) NOT NULL ,
    RATING NUMBER NOT NULL,
    CONSTRAINT FK_ORGANIZATION_REVIEW_TO_ORGANIZATION FOREIGN KEY (ORGANIZATION_ID)
        REFERENCES TBL_ORGANIZATION (ORGANIZATION_ID) ON DELETE CASCADE,
    CONSTRAINT FK_ORGANIZATION_REVIEW_TO_USER FOREIGN KEY (USER_ID)
        REFERENCES TBL_USER (USER_ID) ON DELETE CASCADE
);

CREATE TABLE TBL_ANONYMOUS
(
    ANONYMOUS_ID  NUMBER PRIMARY KEY,
    USER_ID          NUMBER    NOT NULL,
    TITLE VARCHAR2(100) NOT NULL ,
    CONTENT VARCHAR2(1000) NOT NULL ,
    CREATED_DATE DATE DEFAULT SYSDATE,
    VIEWS NUMBER DEFAULT 0,
    CONSTRAINT FK_ANONYMOUS_TO_USER FOREIGN KEY (USER_ID)
        REFERENCES TBL_USER (USER_ID) ON DELETE CASCADE
);

CREATE TABLE TBL_ANONYMOUS_COMMENT
(
    ANONYMOUS_COMMENT_ID  NUMBER PRIMARY KEY,
    ANONYMOUS_ID NUMBER    NOT NULL,
    USER_ID          NUMBER    NOT NULL,
    CONTENT VARCHAR2(100) NOT NULL ,
    CREATED_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT FK_ANONYMOUS_COMMENT_TO_ANONYMOUS FOREIGN KEY (ANONYMOUS_ID)
        REFERENCES TBL_ANONYMOUS (ANONYMOUS_ID) ON DELETE CASCADE,
    CONSTRAINT FK_ANONYMOUS_COMMENT_TO_USER FOREIGN KEY (USER_ID)
        REFERENCES TBL_USER (USER_ID) ON DELETE CASCADE
);

CREATE TABLE TBL_ANNOUNCEMENT
(
    ANNOUNCEMENT_ID  NUMBER PRIMARY KEY,
    TITLE VARCHAR2(100) NOT NULL,
    CONTENT VARCHAR2(100) NOT NULL ,
    CREATED_DATE DATE DEFAULT SYSDATE
);


CREATE TABLE TBL_STORY
(
    STORY_ID  NUMBER PRIMARY KEY,
    USER_ID          NUMBER    NOT NULL,
    ANONYMOUS_ID NUMBER    NOT NULL,
    APPLIED_VOLUNTEER_ID NUMBER NOT NULL,
    TITLE VARCHAR2(1000) NOT NULL,
    CONTENT VARCHAR2(100) NOT NULL ,
    CREATED_DATE DATE DEFAULT SYSDATE,
    VIEWS NUMBER DEFAULT 0,
    CONSTRAINT FK_STORY_TO_USER FOREIGN KEY (USER_ID)
        REFERENCES TBL_USER (USER_ID) ON DELETE CASCADE,
    CONSTRAINT FK_STORY_TO_APPLIED_VOLUNTEER FOREIGN KEY (APPLIED_VOLUNTEER_ID)
        REFERENCES TBL_APPLIED_VOLUNTEER (APPLIED_VOLUNTEER_ID) ON DELETE CASCADE
);

CREATE TABLE TBL_STORY_IMG
(
    STORY_IMG_ID  NUMBER PRIMARY KEY,
    STORY_ID          NUMBER    NOT NULL,
    FILE_LOCATION VARCHAR2(100) NOT NULL,
    CONSTRAINT FK_STORY_IMG_TO_STORY FOREIGN KEY (STORY_ID )
        REFERENCES TBL_STORY (STORY_ID ) ON DELETE CASCADE
);

CREATE TABLE TBL_STORY_COMMENT
(
    STORY_COMMENT_ID  NUMBER PRIMARY KEY,
    STORY_ID NUMBER    NOT NULL,
    USER_ID          NUMBER    NOT NULL,
    CONTENT VARCHAR2(100) NOT NULL ,
    CREATED_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT FK_STORY_COMMENT_TO_STORY FOREIGN KEY (STORY_ID)
        REFERENCES TBL_ANONYMOUS (ANONYMOUS_ID) ON DELETE CASCADE,
    CONSTRAINT FK_STORY_COMMENT_TO_USER FOREIGN KEY (USER_ID)
        REFERENCES TBL_USER (USER_ID) ON DELETE CASCADE
);

CREATE TABLE TBL_STORY_LIKE
(
    STORY_LIKE_ID  NUMBER PRIMARY KEY,
    STORY_ID NUMBER    NOT NULL,
    USER_ID          NUMBER    NOT NULL,
    CONSTRAINT FK_STORY_LIKE_TO_STORY FOREIGN KEY (STORY_ID)
        REFERENCES TBL_ANONYMOUS (ANONYMOUS_ID) ON DELETE CASCADE,
    CONSTRAINT FK_STORY_LIKE_TO_USER FOREIGN KEY (USER_ID)
        REFERENCES TBL_USER (USER_ID) ON DELETE CASCADE
);











