CREATE SEQUENCE seq_users
    START WITH 1
    INCREMENT BY 1
    NOCACHE;

-- 마이페이지 유저들의 테이블
CREATE TABLE TBL_USERS
(
    PROFILE_PIC VARCHAR2(255),
    PROVIDER_NAME VARCHAR2(50),
    PROVIDER_ID VARCHAR2(255) PRIMARY KEY,
    LOCATION VARCHAR2(255),
    QUALIFICATIONS VARCHAR2(255),
    CREATE_AT DATE,
    UPDATE_AT DATE,

);
-- 마이페이지 봉사기록들의 테이블
CREATE TABLE TBL_VOLUNTEER_ACTIVITIES
(
    TITLE VARCHAR2(100),
    DATE DATE,
    ORGANIZATION VARCHAR2(255),
    VOLUNTEER_POST_ID VARCHAR2(255) PRIMARY KEY,
    CREATE_AT DATE,
    UPDATE_AT DATE,
    PROVIDER_ID VARCHAR2(255),
    FOREIGN KEY (PROVIDER_ID) REFERENCES TBL_USERS(PROVIDER_ID)
);

-- 게시물 테이블(마이페이지 각 게시물 모달 띄울 부분)
CREATE TABLE posts(
    POST_ID VARCHAR2(500) PRIMARY KEY,
    CONTENT TEXT,
    LIKES NUMBER,
    PROVIDER_ID VARCHAR2(255),
    CREATE_AT DATE,
    UPDATE_AT DATE,
    FOREIGN KEY (PROVIDER_ID) REFERENCES TBL_USERS(PROVIDER_ID)
);

-- 게시물의 댓글 테이블 (마이페이지 각 게시물 모달의 댓글)
CREATE TABLE COMMENTS(
    COMMENT_ID NUMBER PRIMARY KEY,
    PROVIDER_ID PRIMARY KEY,
    POST_ID VARCHAR2(500),
    COMMENT_CONTENT VARCHAR2(1000) NOT NULL,
    COMMENT_REGISTER_DATE DATE,
    COMMENT_UPDATE_DATE   DATE,
    FOREIGN KEY(POST_ID) REFERENCES posts(POST_ID),
    FOREIGN KEY (PROVIDER_ID) REFERENCES TBL_USERS(PROVIDER_ID)
);





















