-- Drop sequence
DROP SEQUENCE SEQ_LOCATION;
DROP SEQUENCE SEQ_ORGANIZATION;
DROP SEQUENCE SEQ_USER;
DROP SEQUENCE SEQ_VOLUNTEER;
DROP SEQUENCE SEQ_APPLIED_VOLUNTEER;
DROP SEQUENCE SEQ_USER_NOTIFICATION;
DROP SEQUENCE SEQ_ORGANIZATION_NOTIFICATION;
DROP SEQUENCE SEQ_USER_REVIEW;
DROP SEQUENCE SEQ_ORGANIZATION_REVIEW;
DROP SEQUENCE SEQ_ANONYMOUS;
DROP SEQUENCE SEQ_ANONYMOUS_COMMENT;
DROP SEQUENCE SEQ_ANNOUNCEMENT;
DROP SEQUENCE SEQ_STORY;
DROP SEQUENCE SEQ_STORY_IMG;
DROP SEQUENCE SEQ_STORY_COMMENT;
DROP SEQUENCE SEQ_STORY_LIKE;

-- Drop table
DROP TABLE TBL_LOCATION cascade constraints ;
DROP TABLE TBL_ORGANIZATION cascade constraints;
DROP TABLE TBL_USER cascade constraints;
DROP TABLE TBL_VOLUNTEER cascade constraints;
DROP TABLE TBL_APPLIED_VOLUNTEER cascade constraints;
DROP TABLE TBL_USER_NOTIFICATION cascade constraints;
DROP TABLE TBL_ORGANIZATION_NOTIFICATION cascade constraints;
DROP TABLE TBL_USER_REVIEW cascade constraints;
DROP TABLE TBL_ORGANIZATION_REVIEW cascade constraints;
DROP TABLE TBL_ANONYMOUS cascade constraints;
DROP TABLE TBL_ANONYMOUS_COMMENT cascade constraints;
DROP TABLE TBL_ANNOUNCEMENT cascade constraints;
DROP TABLE TBL_STORY cascade constraints;
DROP TABLE TBL_STORY_IMG cascade constraints;
DROP TABLE TBL_STORY_COMMENT cascade constraints;
DROP TABLE TBL_STORY_LIKE cascade constraints;


